configs:
  params:
    server.insecure: true

redis:
  resources:
    limits:
      cpu: 128m
      memory: 128Mi
    requests:
      cpu: 64m
      memory: 64Mi

controller:
  resources:
    limits:
      cpu: 128m
      memory: 512Mi
    requests:
      cpu: 64m
      memory: 256Mi

dex:
  resources:
    limits:
      cpu: 128m
      memory: 128Mi
    requests:
      cpu: 64m
      memory: 64Mi

server:
  resources:
    limits:
      cpu: 128m
      memory: 512Mi
    requests:
      cpu: 64m
      memory: 64Mi

repoServer:
  resources:
    limits:
      cpu: 128m
      memory: 512Mi
    requests:
      cpu: 64m
      memory: 64Mi

applicationSet:
  resources:
    limits:
      cpu: 128m
      memory: 128Mi
    requests:
      cpu: 64m
      memory: 64Mi

notifications:
  resources:
    limits:
      cpu: 128m
      memory: 128Mi
    requests:
      cpu: 64m
      memory: 64Mi
